QtImageViewer/QtImageViewer.cxx

ImageViewer prints the image file name that is loaded, but no
new line character was inserted. After exiting ImageViewer, the
new prompt line was written after the file name that had been loaded
instead of being written on a clean new line.

ENH: Missing new line character when printing input file name.

---

.travis.yml

ImageViewer does not use FLTK anymore. All references to FLTK have been removed and replaced by Qt.

ENH: TravisCI is now configured with Qt4

---

CMake/Superbuild/External_SlicerExecutionModel.cmake

In a previous commit (5480a6b32aec3df372f08fc18882e8646ca8b8a5 [1]), External_SlicerExecutionModel.cmake has been modified and does not check if SlicerExecutionModel_DIR is defined before creating the external project to download and compile SlicerExecutionModel. Even if it is provided and if USE_SYSTEM_SLICER_EXECUTION_MODEL is set to ON, the external project for SlicerExecutionModel was still used.
[1] https://github.com/KitwareMedical/ImageViewer/commit/5480a6b32aec3df372f08fc18882e8646ca8b8a5#diff-2ead5608565906a4e7f5d574e7363861

ENH: Do not build SlicerExecutionModel if its path is provided

---

QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h

GlSliceView provides callbacks for when a point is selected by the
user.  This update adds member functions to set those callbacks in the
Qt version.

ENH: Add member functions that enable specification of callbacks

---

ImageViewer/ImageViewer.cxx

Interactivity degrades with too large of a morphology radius.  Instead
of the radius being proportional to the distance the mouse was dragged,
in this version it is fixed at 2 voxels.  The assumption is that most
image noise is on the order of 1 voxels.   Meh.

ENH: Fix morphology radius to 2 voxels

---

ImageViewer/ImageViewer.cxx
ImageViewer/ImageViewer.xml
QtImageViewer/CMakeLists.txt
QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h
QtImageViewer/QtImageViewer.cxx
QtImageViewer/Resources/UI/QtImageViewer.ui
QtImageViewer/RulerWidget.cxx
QtImageViewer/RulerWidget.h

Added a Ruler Widget that allows multiple rulers to be overlayed on an image and exported to JSON.
Added a new cClickMode CM_RULER.  Moved the screen to image index calculation in QtGlSliceView into its
own function and added the inverse and physical point transforms.
Added a new flag -R --ONSDRuler that changes the default ruler style to ONSD to the CLI app.
Added a new key input, 'u' that switches the ruler mode and ctrl-U that saves the ruler output to JSON.
Updated help information with usage.
Two modes to ruler, a "rainbow" mode that cycles between 7 colors and monotonically names each ruler and
a ONSD mode that has an "R1" and "ONSD" measure that is for the 3mm ocular orb distance and ONSD.
Rulers are placed with left-click and moved or deleted with right-click when in CM_RULER.
Use …

ENH: Ruler Widget

---

CMakeLists.txt
ImageViewer/ImageViewer.cxx
ImageViewer/ImageViewer.xml
QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h
QtImageViewer/QtImageViewer.h

New options to specify initial mouse mode (e.g., paint / select),
paint initial color, paint initial radius, and filename to auto save
overlay on exit.

ENH: Save overlay on exit

---

ImageViewer/ImageViewer.cxx
ImageViewer/ImageViewer.xml
QtImageViewer/BoxWidget.cxx
QtImageViewer/BoxWidget.h
QtImageViewer/CMakeLists.txt
QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h

- ROI box widget is now available.
- Save-on-exit logic extends to saving everything (rulers, overlays, boxes).
The `-S` option is now named "saveOnExit". This takes a filename prefix which, when ImageViewer exits, is used to determine the final filename for saved annotations. In addition, there is a new option `--overlayImageExtension` which takes in a valid image extension, e.g. "nrrd". The default is "mha".
- for overlays, the filename is `prefix + ".overlay." + overlayImageExtension`
- for rulers/boxes, the filename is `prefix + ".[rulers|boxes].json"`.

ENH: ROI boxes and save-on-exit logic

---

ImageViewer/ImageViewer.cxx
ImageViewer/ImageViewer.xml
QtImageViewer/BoxWidget.cxx
QtImageViewer/BoxWidget.h
QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h
QtImageViewer/QtImageViewer.cxx
QtImageViewer/QtImageViewer.h

This adds a switch `-n` to read in box annotations and display them. Specifying multiple `-n` switches will read in multiple annotation files.
Other fixes:
- boxes now show even if the mode is not on box widget
Notes:
- the changes do not allow for reading in ruler annotations yet

ENH: Read in box annotations

---

ImageViewer/ImageViewer.cxx
QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h
QtImageViewer/RulerWidget.cxx
QtImageViewer/RulerWidget.h

Adds a ruler workflow, similar to the paint and bounding box workflows.
Workflow string is "r" or "R", and users can optionally specify "o" for the onsd measurement specific features.

Add ruler workflow

---

ImageViewer/ImageViewer.cxx
ImageViewer/ImageViewer.xml
QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h

Adds `--preserveOverlayPaint`, which will prevent overwriting already painted voxels.

ENH: add preserveOverlayPaint flag

---

QtImageViewer/QtGlSliceView.cxx

OverlayOpacity was being reset when a new overlay was created. When
starting painting, it would create an overlay, and thereby reset
opacity.  So, opacity values passed on the command line were ignored.
Also, when display of "values" (details in lower right) were toggled,
the mode "select/paint/ruler/..." was still being displayed.  Now
it's display is appropriately toggled as well.

BUG: Overlay opacity was being overwritten - also hide select with value

---

QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h

Hi All,
I've added a feature that uses ITK's Morphological Contour Interpolator to interpolate paint overlays across slices. Paint slice X and jump a bunch of slices and paint slice Y. Then hit Ctrl + P for the interpolation. The slices that were not painted in between will be filled in.
Kindly review the changes and let me know if there are modifications needed here.
Thank you,
Barry

Interpolate paint overlay across slices

---

ImageViewer/ImageViewer.cxx
ImageViewer/ImageViewer.xml
QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h

Use shift-U to undo most recent brush stroke or interpolation.
Allow optional persistent workflows that don't revert workflow
state when moving to a new slice.

ENH: Add persistent workflows and one level of undo

---

QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h

Moves `QtGlSliceView::addBox` out of the `public slots` section. As far as I can tell, it isn't used as a slot

QtGlSliceView: Move addBox out of slots

---

QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h
QtImageViewer/QtImageViewer.cxx
QtImageViewer/QtImageViewer.h
QtImageViewer/RulerWidget.cxx
QtImageViewer/RulerWidget.h

Load in ruler annotations. Resolves #118 
Other changes:
* Write out ruler annotation metadata to json
* Use the metadata to reinitialize the state of the onsd and rainbow metadata generators, so the user can pick up where they left off after reading in annotations
TODO:

ENH: Load ruler annotations

---

QtImageViewer/QtGlSliceView.cxx

Switches the definition of [`setIsONSDRuler`](https://github.com/KitwareMedical/ImageViewer/blob/master/QtImageViewer/QtGlSliceView.cxx#L3165) to change the underlying `isONSDRuler` to the passed in flag. Previously, the function would just toggle the underlying flag, ignoring the parameter.
As an MRE, run `ImageViewer`, and try drawing a ruler. Notice that the ruler is an onsd ruler, despite the `isONSDRuler` flag being set to false in the [constructor](https://github.com/KitwareMedical/ImageViewer/blob/master/QtImageViewer/QtGlSliceView.cxx#L195)
This is due to the switch that happens in [`ImageViewer.cxx`](https://github.com/KitwareMedical/ImageViewer/blob/master/ImageViewer/ImageViewer.cxx#L431). If the `-R` flag is not present, the `setIsONSDRuler` call shouldn't change the value of …

BUG: Fix `setIsONSDRuler`

---

ImageViewer/ImageViewer.cxx
QtImageViewer/QtGlSliceView.cxx
QtImageViewer/QtGlSliceView.h
QtImageViewer/QtImageViewer.cxx
QtImageViewer/QtImageViewer.h

Adds the ability to put text in the upper right corner. By pressing the `g` key, a dialog box will pop up, which can be populated with text. Press OK, and the text will appear in the top right
Default text for the dialog box can also be specified with `./ImageViewer <image_path> -w "t,default_text_here"`
Supports the saving and loading of annotations
TODO:

ENH: Add corner text

---

QtImageViewer/QtGlSliceView.cxx

By default, workflow steps are incremented on a frame change. When a frame change was detected, the workflow step would first be incremented, then the frame would be changed. The order has been switched here (frame is changed first, then the workflow step). When the workflow step is changed, the metadata factory for whatever tool is being used (box, ruler, etc.) is updated for the _current_ frame. If the frame hasn't changed yet (as was previously the case), it will have no effect. Then, after the frame has changed, the default factory from the [constructor](https://github.com/KitwareMedical/ImageViewer/blob/master/QtImageViewer/QtGlSliceView.cxx#L199) will be used to generate new objects.
As an MRE, run:
`./ImageViewer <path_to_file> -w "b,ROI,1"`. Left click to draw a bounding box (it …

BUG: Switch workflow steps after frame is changed

---

CMakeLists.txt
README.md

`QFontMetrics.horizontalAdvance` not added until Qt 5.11: https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance
Updates the minimum required qt version in the `CMakeLists.txt` and adds a note to the readme

CMakeLists.txt: Update minimum qt version required

---

QtImageViewer/QtGlSliceView.cxx

Added shift-space as a command to move the workflow step backwards. Also added missing documentation for space / shift-space commands.

ENH: Add shift-space to move workflow back

---

QtImageViewer/QtGlSliceView.cxx

If the window isn't square, it would cause the aspect ratio of the image voxel size to become incorrect.
Now the image voxel spacing doesn't appear to change if the height/width ratio of the window isn't 1.

BUG: Image voxel aspect ratio changed when window resized
